version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: deeptrust_postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: deeptrust

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend

    container_name: deeptrust_backend

    depends_on:
      - postgres

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql://postgres:1234@postgres:5432/deeptrust


  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend

    container_name: deeptrust_frontend

    depends_on:
      - backend

    ports:
      - "5173:5173"


volumes:
  postgres_data: